CREATE TABLE auth (
    uid INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    userid INT UNSIGNED NOT NULL,
    time INT UNSIGNED NOT NULL DEFAULT 0,
    start INT UNSIGNED NOT NULL DEFAULT 0,
    confirmed INT(1) UNSIGNED NOT NULL DEFAULT 0,
    auth CHAR(255) NOT NULL DEFAULT '',
    useragent VARCHAR(100) NOT NULL DEFAULT '',
    remoteip VARCHAR(40) NOT NULL DEFAULT '',
    remotehost VARCHAR(256) NOT NULL DEFAULT ''
);
CREATE INDEX idxAuthUserId ON auth(userid) USING HASH;